#!/usr/bin/env bash
# this script to displays the visitor IP along with the HTTP status code from the Apache log file.

# Check if the apache-access.log file exists
if [ ! -f "apache-access.log" ]; then
    echo "Error: apache-access.log file not found."
    exit 1
fi

awk '{print $1, $9}' apache-access.log
